wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720087565
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 23
      4: 3.12.2
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
input_image_size:
  desc: null
  value:
  - 224
  - 224
train_csv_file:
  desc: null
  value: manifest/dummy-set/image_pairs_train.csv
val_csv_file:
  desc: null
  value: manifest/dummy-set/image_pairs_val.csv
test_csv_file:
  desc: null
  value: manifest/dummy-set/image_pairs_test.csv
root_dir:
  desc: null
  value: /home/jeans/internship/resources/datasets/mon
continue_from_checkpoint:
  desc: null
  value: false
checkpoint_root:
  desc: null
  value: null
batch_size:
  desc: null
  value: 8
num_epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 1.0e-05
scheduler_step_size:
  desc: null
  value: 5
scheduler_gamma:
  desc: null
  value: 0.1
num_classes:
  desc: null
  value: 3
image_size:
  desc: null
  value: 224
depth_vit:
  desc: null
  value: 1
heads:
  desc: null
  value: 4
out_dim:
  desc: null
  value: 1024
